### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by sameenashaikh29** [MrVallentin/mount.py#2]
Given the directions, i am not able to install this library on my raspberry pi. i used these instructions
$ git clone https://github.com/MrVallentin/mount.py
$ sudo python mount.py/setup.py install
$ rm -rf mount.py

rm -rf mount.py doesnt work for me so i did sudo rm -rf mount.py

then when i use This command

$ sudo python mount.py/setup.py install --record files.txt

it sayd no such file or directory beacuse i've already deleted that with the rm command right..

Thanks & Regards

**Comment by vallentin** [comment]
> `rm -rf mount.py` doesn't work for me so i did `sudo rm -rf mount.py`

I should probably have added a note related to permissions. But yes, if the user you used doesn't have permission to delete the file, then elevating the user by prefixing commands with `sudo` makes sense.

> It say's no such file or directory

The easiest way is to clone the repo again and then run the command. This is also noted in the README.

> Download the module using any of the above, and then do the following:
>
>     sudo python mount.py/setup.py install --record files.txt
>     $ cat mount.py/files.txt | sudo xargs rm -rf
